//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchDataEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public long Id { get; set; }
        public string Nome { get; set; }
        public Nullable<long> TipoFile { get; set; }
        public string DirectoryInput { get; set; }
        public string DirectoryOutput { get; set; }
        public Nullable<long> NumDoc { get; set; }
        public Nullable<long> NumPages { get; set; }
        public Nullable<long> DocCorrente { get; set; }
        public Nullable<long> UltimoIndicizzato { get; set; }
        public long FKModello { get; set; }
    
        public virtual Modello Modello { get; set; }
    }
}
