//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchDataEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campo
    {
        public long Id { get; set; }
        public string Nome { get; set; }
        public Nullable<long> SalvaValori { get; set; }
        public string ValorePredefinito { get; set; }
        public Nullable<long> IndicePrimario { get; set; }
        public Nullable<long> TipoCampo { get; set; }
        public long FKModello { get; set; }
    
        public virtual Modello Modello { get; set; }
    }
}
