//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchDataEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modello
    {
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public long OrigineCsv { get; set; }
        public Nullable<long> FKCsv { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Campo Campo { get; set; }
        public virtual OrigineDatiCSV OrigineDatiCSV { get; set; }
    }
}
