//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchDataEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrigineDatiCSV
    {
        public long Id { get; set; }
        public string Path { get; set; }
        public string Separatore { get; set; }
    
        public virtual Modello Modello { get; set; }
    }
}
